--!strict
local ALIASES = {
	["ComicNeueAngular.json"] = {
		"Comic Neue",
	},
	["GrenzeGotish.json"] = {
		"Grenze",
	},
	["SourceSansPro.json"] = {
		"Source Sans 3",
	},
	["12187370000"] = {
		"Bungee",
	},
	["12187607493"] = {
		"Shadows Into Light Two",
	},
	["12187376357"] = {
		"Sedgwick Ave",
	},
	["12187365104"] = {
		"Blaka Ink",
	},
	["8836875837"] = {
		"Lobster Two",
	},
	["12187374765"] = {
		"Playfair Display SC",
	},
	["12187370747"] = {
		"Noto Color Emoji",
		"Noto Sans Symbols",
		"Noto Sans Symbols2",
	},
	["12187369802"] = {
		"Caveat Brush",
	},
	["12188570269"] = {
		"Rounded Mplus 1c",
		"Rounded Mplus 1c Bold",
	},
	["12187365559"] = {
		"Mukta Mahee",
		"Mukta Malar",
		"Mukta Vaani",
	},
	["12187606934"] = {
		"PT Sans Caption",
	},
}

return ALIASES
